package net.dgg.cloud.entity;

public class CallRecord {
    /** 通话唯一标识 */
    private String callId;

    /** 应用id */
    private String appId;

    /** 本次呼叫的主叫号码 */
    private String callerNum;

    /** 本次呼叫的被叫号码 */
    private String calleeNum;

    /** 中间号 */
    private String servingNum;

    /** axyb的y号码 */
    private String yNum;

    /** 本次通话的开始时间 */
    private String startTime;

    /** 本次通话的结束时间 */
    private String endTime;

    /** 被叫接听时间 */
    private String answerTime;

    /** 本次通话的结果 （见第7节通话结果） */
    private String result;

    /** '1" 表示主叫， "2" 表示被叫， "0" 表示平台释放 */
    private String releasedir;

    /** 本次通话的时长，单位为秒 */
    private Integer duration;

    /** "1"：axb  a主叫 "2"：axb  a被叫 "3"：axb  转接 "4"： ax  外呼 "5"： ax  呼入 "7"   axyb a主叫 "8"  axyb  a被叫 */
    private String calltype;

    /** 映射关系ID */
    private String mappingId;

    /** 被叫振铃时间 */
    private String calleeRingTime;

    /** 录音地址 */
    private String recordUrl;

    /** 用户自定义数据 */
    private String userData;

    /** salesman_id */
    private String salesmanId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.call_id
     *
     * @return the value of call_record.call_id
     *
     * @mbggenerated
     */
    public String getCallId() {
        return callId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.call_id
     *
     * @param callId the value for call_record.call_id
     *
     * @mbggenerated
     */
    public void setCallId(String callId) {
        this.callId = callId == null ? null : callId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.app_id
     *
     * @return the value of call_record.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.app_id
     *
     * @param appId the value for call_record.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.caller_num
     *
     * @return the value of call_record.caller_num
     *
     * @mbggenerated
     */
    public String getCallerNum() {
        return callerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.caller_num
     *
     * @param callerNum the value for call_record.caller_num
     *
     * @mbggenerated
     */
    public void setCallerNum(String callerNum) {
        this.callerNum = callerNum == null ? null : callerNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.callee_num
     *
     * @return the value of call_record.callee_num
     *
     * @mbggenerated
     */
    public String getCalleeNum() {
        return calleeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.callee_num
     *
     * @param calleeNum the value for call_record.callee_num
     *
     * @mbggenerated
     */
    public void setCalleeNum(String calleeNum) {
        this.calleeNum = calleeNum == null ? null : calleeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.serving_num
     *
     * @return the value of call_record.serving_num
     *
     * @mbggenerated
     */
    public String getServingNum() {
        return servingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.serving_num
     *
     * @param servingNum the value for call_record.serving_num
     *
     * @mbggenerated
     */
    public void setServingNum(String servingNum) {
        this.servingNum = servingNum == null ? null : servingNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.y_num
     *
     * @return the value of call_record.y_num
     *
     * @mbggenerated
     */
    public String getyNum() {
        return yNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.y_num
     *
     * @param yNum the value for call_record.y_num
     *
     * @mbggenerated
     */
    public void setyNum(String yNum) {
        this.yNum = yNum == null ? null : yNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.start_time
     *
     * @return the value of call_record.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.start_time
     *
     * @param startTime the value for call_record.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.end_time
     *
     * @return the value of call_record.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.end_time
     *
     * @param endTime the value for call_record.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.answer_time
     *
     * @return the value of call_record.answer_time
     *
     * @mbggenerated
     */
    public String getAnswerTime() {
        return answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.answer_time
     *
     * @param answerTime the value for call_record.answer_time
     *
     * @mbggenerated
     */
    public void setAnswerTime(String answerTime) {
        this.answerTime = answerTime == null ? null : answerTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.result
     *
     * @return the value of call_record.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.result
     *
     * @param result the value for call_record.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.releasedir
     *
     * @return the value of call_record.releasedir
     *
     * @mbggenerated
     */
    public String getReleasedir() {
        return releasedir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.releasedir
     *
     * @param releasedir the value for call_record.releasedir
     *
     * @mbggenerated
     */
    public void setReleasedir(String releasedir) {
        this.releasedir = releasedir == null ? null : releasedir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.duration
     *
     * @return the value of call_record.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.duration
     *
     * @param duration the value for call_record.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.calltype
     *
     * @return the value of call_record.calltype
     *
     * @mbggenerated
     */
    public String getCalltype() {
        return calltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.calltype
     *
     * @param calltype the value for call_record.calltype
     *
     * @mbggenerated
     */
    public void setCalltype(String calltype) {
        this.calltype = calltype == null ? null : calltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.mapping_id
     *
     * @return the value of call_record.mapping_id
     *
     * @mbggenerated
     */
    public String getMappingId() {
        return mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.mapping_id
     *
     * @param mappingId the value for call_record.mapping_id
     *
     * @mbggenerated
     */
    public void setMappingId(String mappingId) {
        this.mappingId = mappingId == null ? null : mappingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.callee_ring_time
     *
     * @return the value of call_record.callee_ring_time
     *
     * @mbggenerated
     */
    public String getCalleeRingTime() {
        return calleeRingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.callee_ring_time
     *
     * @param calleeRingTime the value for call_record.callee_ring_time
     *
     * @mbggenerated
     */
    public void setCalleeRingTime(String calleeRingTime) {
        this.calleeRingTime = calleeRingTime == null ? null : calleeRingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.record_url
     *
     * @return the value of call_record.record_url
     *
     * @mbggenerated
     */
    public String getRecordUrl() {
        return recordUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.record_url
     *
     * @param recordUrl the value for call_record.record_url
     *
     * @mbggenerated
     */
    public void setRecordUrl(String recordUrl) {
        this.recordUrl = recordUrl == null ? null : recordUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.user_data
     *
     * @return the value of call_record.user_data
     *
     * @mbggenerated
     */
    public String getUserData() {
        return userData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.user_data
     *
     * @param userData the value for call_record.user_data
     *
     * @mbggenerated
     */
    public void setUserData(String userData) {
        this.userData = userData == null ? null : userData.trim();
    }

    public String getSalesmanId() {
        return salesmanId;
    }

    public void setSalesmanId(String salesmanId) {
        this.salesmanId = salesmanId;
    }
}