package net.dgg.cloud.entity;

import java.util.List;

/**
 * 区域信息表
 */
public class ConRegion {
    /** ID */
    private String id;

    /** 城市名 */
    private String name;

    /** 父ID */
    private String pid;

    /** 英文名 */
    private String nameEn;

    private List<ConRegion> ConRegionChild;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_region.id
     *
     * @return the value of con_region.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_region.id
     *
     * @param id the value for con_region.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_region.name
     *
     * @return the value of con_region.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_region.name
     *
     * @param name the value for con_region.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_region.pid
     *
     * @return the value of con_region.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_region.pid
     *
     * @param pid the value for con_region.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column con_region.name_en
     *
     * @return the value of con_region.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column con_region.name_en
     *
     * @param nameEn the value for con_region.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    public List<ConRegion> getConRegionChild() {
        return ConRegionChild;
    }

    public void setConRegionChild(List<ConRegion> conRegionChild) {
        ConRegionChild = conRegionChild;
    }
}