package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 业态
 */
public class XdBusiness {
    /** 主键id */
    private String id;

    /** 业态名称 */
    private String businessName;

    /** 父节点 */
    private String parentId;

    /** 层次关系(一级从0开始) */
    private Integer level;

    /** 创建人id */
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    private String updateUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 删除标识（0-正常，1删除） */
    private Integer delFlag;

    /** 排序值 */
    private Integer orderNo;


    /** 业态code ，二期新增*/
    private String code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.id
     *
     * @return the value of xd_business.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.id
     *
     * @param id the value for xd_business.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.business_name
     *
     * @return the value of xd_business.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.business_name
     *
     * @param businessName the value for xd_business.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.parent_id
     *
     * @return the value of xd_business.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.parent_id
     *
     * @param parentId the value for xd_business.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.level
     *
     * @return the value of xd_business.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.level
     *
     * @param level the value for xd_business.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.create_user_id
     *
     * @return the value of xd_business.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.create_user_id
     *
     * @param createUserId the value for xd_business.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.create_time
     *
     * @return the value of xd_business.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.create_time
     *
     * @param createTime the value for xd_business.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.update_user_id
     *
     * @return the value of xd_business.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.update_user_id
     *
     * @param updateUserId the value for xd_business.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.update_time
     *
     * @return the value of xd_business.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.update_time
     *
     * @param updateTime the value for xd_business.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.del_flag
     *
     * @return the value of xd_business.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.del_flag
     *
     * @param delFlag the value for xd_business.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_business.order_no
     *
     * @return the value of xd_business.order_no
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_business.order_no
     *
     * @param orderNo the value for xd_business.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}