package net.dgg.cloud.entity;

import java.util.Date;

public class XdCallNum {
    /** 主键id */
    private String id;

    /** 商务id */
    private String salesmanId;

    /** 统计日期 */
    private Date statisticsDate;

    /** 打电话次数 */
    private Integer callNum;

    /** 坐席号 */
    private String seatNum;

    /** 创建时间 */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_call_num.id
     *
     * @return the value of xd_call_num.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_call_num.id
     *
     * @param id the value for xd_call_num.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_call_num.salesman_id
     *
     * @return the value of xd_call_num.salesman_id
     *
     * @mbggenerated
     */
    public String getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_call_num.salesman_id
     *
     * @param salesmanId the value for xd_call_num.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(String salesmanId) {
        this.salesmanId = salesmanId == null ? null : salesmanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_call_num.statistics_date
     *
     * @return the value of xd_call_num.statistics_date
     *
     * @mbggenerated
     */
    public Date getStatisticsDate() {
        return statisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_call_num.statistics_date
     *
     * @param statisticsDate the value for xd_call_num.statistics_date
     *
     * @mbggenerated
     */
    public void setStatisticsDate(Date statisticsDate) {
        this.statisticsDate = statisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_call_num.call_num
     *
     * @return the value of xd_call_num.call_num
     *
     * @mbggenerated
     */
    public Integer getCallNum() {
        return callNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_call_num.call_num
     *
     * @param callNum the value for xd_call_num.call_num
     *
     * @mbggenerated
     */
    public void setCallNum(Integer callNum) {
        this.callNum = callNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_call_num.seat_num
     *
     * @return the value of xd_call_num.seat_num
     *
     * @mbggenerated
     */
    public String getSeatNum() {
        return seatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_call_num.seat_num
     *
     * @param seatNum the value for xd_call_num.seat_num
     *
     * @mbggenerated
     */
    public void setSeatNum(String seatNum) {
        this.seatNum = seatNum == null ? null : seatNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_call_num.create_time
     *
     * @return the value of xd_call_num.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_call_num.create_time
     *
     * @param createTime the value for xd_call_num.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}