package net.dgg.cloud.entity;

import java.util.Date;

public class XdClue {
    /** 主键id */
    private String id;

    /** 资源来源id */
    private String sourceId;

    /** 省份id */
    private String provinceId;

    /** 城市id */
    private String cityId;

    /** 一级业态id */
    private String bigBizId;

    /** 二级业态id */
    private String smallBizId;

    /** 顾客名称 */
    private String customerName;

    /** 顾客电话 */
    private String customerPhone;

    /** 客户性别（0待定，1男，2女） */
    private Integer customerSex;

    /** 备注 */
    private String message;

    /** 状态（0：普通线索状态，1：转化成果状态，2：无效状态） */
    private Integer status;

    /** 创建时间 */
    private Date createTime;

    /** 修改时间 */
    private Date updateTime;

    /** 修改用户id */
    private String updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.id
     *
     * @return the value of xd_clue.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.id
     *
     * @param id the value for xd_clue.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.source_id
     *
     * @return the value of xd_clue.source_id
     *
     * @mbggenerated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.source_id
     *
     * @param sourceId the value for xd_clue.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.province_id
     *
     * @return the value of xd_clue.province_id
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.province_id
     *
     * @param provinceId the value for xd_clue.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.city_id
     *
     * @return the value of xd_clue.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.city_id
     *
     * @param cityId the value for xd_clue.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.big_biz_id
     *
     * @return the value of xd_clue.big_biz_id
     *
     * @mbggenerated
     */
    public String getBigBizId() {
        return bigBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.big_biz_id
     *
     * @param bigBizId the value for xd_clue.big_biz_id
     *
     * @mbggenerated
     */
    public void setBigBizId(String bigBizId) {
        this.bigBizId = bigBizId == null ? null : bigBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.small_biz_id
     *
     * @return the value of xd_clue.small_biz_id
     *
     * @mbggenerated
     */
    public String getSmallBizId() {
        return smallBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.small_biz_id
     *
     * @param smallBizId the value for xd_clue.small_biz_id
     *
     * @mbggenerated
     */
    public void setSmallBizId(String smallBizId) {
        this.smallBizId = smallBizId == null ? null : smallBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.customer_name
     *
     * @return the value of xd_clue.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.customer_name
     *
     * @param customerName the value for xd_clue.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.customer_phone
     *
     * @return the value of xd_clue.customer_phone
     *
     * @mbggenerated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.customer_phone
     *
     * @param customerPhone the value for xd_clue.customer_phone
     *
     * @mbggenerated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.customer_sex
     *
     * @return the value of xd_clue.customer_sex
     *
     * @mbggenerated
     */
    public Integer getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.customer_sex
     *
     * @param customerSex the value for xd_clue.customer_sex
     *
     * @mbggenerated
     */
    public void setCustomerSex(Integer customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.message
     *
     * @return the value of xd_clue.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.message
     *
     * @param message the value for xd_clue.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.status
     *
     * @return the value of xd_clue.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.status
     *
     * @param status the value for xd_clue.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.create_time
     *
     * @return the value of xd_clue.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.create_time
     *
     * @param createTime the value for xd_clue.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.update_time
     *
     * @return the value of xd_clue.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.update_time
     *
     * @param updateTime the value for xd_clue.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_clue.update_user_id
     *
     * @return the value of xd_clue.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_clue.update_user_id
     *
     * @param updateUserId the value for xd_clue.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}