package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 联系人实体
 */
public class XdContacts {
    /** 主键id */
    private String contactsId;

    /** 资源id */
    private String resourcesId;

    /** 客户名称 */
    private String customerName;

    /** 客户电话 */
    private String customerPhoner;

    /** 地址 */
    private String customerAddress;

    /** 所属商务id */
    private String commerceId;

    /** 创建人id */
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    private String updateUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 删除标识(0,未删除 1，删除) */
    private Integer delFlag;

    /** 是否主联系人（0 不是 1是） */
    private Integer isMainCon;

    /** 经度 */
    private String longitude;

    /** 维度 */
    private String latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.contacts_id
     *
     * @return the value of xd_contacts.contacts_id
     *
     * @mbggenerated
     */
    public String getContactsId() {
        return contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.contacts_id
     *
     * @param contactsId the value for xd_contacts.contacts_id
     *
     * @mbggenerated
     */
    public void setContactsId(String contactsId) {
        this.contactsId = contactsId == null ? null : contactsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.resources_id
     *
     * @return the value of xd_contacts.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.resources_id
     *
     * @param resourcesId the value for xd_contacts.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.customer_name
     *
     * @return the value of xd_contacts.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.customer_name
     *
     * @param customerName the value for xd_contacts.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.customer_phoner
     *
     * @return the value of xd_contacts.customer_phoner
     *
     * @mbggenerated
     */
    public String getCustomerPhoner() {
        return customerPhoner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.customer_phoner
     *
     * @param customerPhoner the value for xd_contacts.customer_phoner
     *
     * @mbggenerated
     */
    public void setCustomerPhoner(String customerPhoner) {
        this.customerPhoner = customerPhoner == null ? null : customerPhoner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.customer_address
     *
     * @return the value of xd_contacts.customer_address
     *
     * @mbggenerated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.customer_address
     *
     * @param customerAddress the value for xd_contacts.customer_address
     *
     * @mbggenerated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.commerce_id
     *
     * @return the value of xd_contacts.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.commerce_id
     *
     * @param commerceId the value for xd_contacts.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.create_user_id
     *
     * @return the value of xd_contacts.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.create_user_id
     *
     * @param createUserId the value for xd_contacts.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.create_time
     *
     * @return the value of xd_contacts.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.create_time
     *
     * @param createTime the value for xd_contacts.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.update_user_id
     *
     * @return the value of xd_contacts.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.update_user_id
     *
     * @param updateUserId the value for xd_contacts.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.update_time
     *
     * @return the value of xd_contacts.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.update_time
     *
     * @param updateTime the value for xd_contacts.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.del_flag
     *
     * @return the value of xd_contacts.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.del_flag
     *
     * @param delFlag the value for xd_contacts.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.is_main_con
     *
     * @return the value of xd_contacts.is_main_con
     *
     * @mbggenerated
     */
    public Integer getIsMainCon() {
        return isMainCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.is_main_con
     *
     * @param isMainCon the value for xd_contacts.is_main_con
     *
     * @mbggenerated
     */
    public void setIsMainCon(Integer isMainCon) {
        this.isMainCon = isMainCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.longitude
     *
     * @return the value of xd_contacts.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.longitude
     *
     * @param longitude the value for xd_contacts.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_contacts.latitude
     *
     * @return the value of xd_contacts.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_contacts.latitude
     *
     * @param latitude the value for xd_contacts.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }
}