package net.dgg.cloud.entity;

import java.util.Date;

public class XdGeographyRecords {
    /** 主键id */
    private String id;

    /** 商务id */
    private String commerceId;

    /** 经度 */
    private String longitude;

    /** 纬度 */
    private String latitude;

    /** 当前位置 */
    private String address;

    /** 定位时间 */
    private Date locTime;

    private Long locDate;

    /** 操作人id */
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    private String updateUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 删除标识(0正常，1删除) */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.id
     *
     * @return the value of xd_geography_records.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.id
     *
     * @param id the value for xd_geography_records.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.commerce_id
     *
     * @return the value of xd_geography_records.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.commerce_id
     *
     * @param commerceId the value for xd_geography_records.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.longitude
     *
     * @return the value of xd_geography_records.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.longitude
     *
     * @param longitude the value for xd_geography_records.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.latitude
     *
     * @return the value of xd_geography_records.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.latitude
     *
     * @param latitude the value for xd_geography_records.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.address
     *
     * @return the value of xd_geography_records.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.address
     *
     * @param address the value for xd_geography_records.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.loc_time
     *
     * @return the value of xd_geography_records.loc_time
     *
     * @mbggenerated
     */
    public Date getLocTime() {
        return locTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.loc_time
     *
     * @param locTime the value for xd_geography_records.loc_time
     *
     * @mbggenerated
     */
    public void setLocTime(Date locTime) {
        this.locTime = locTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.create_user_id
     *
     * @return the value of xd_geography_records.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.create_user_id
     *
     * @param createUserId the value for xd_geography_records.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.create_time
     *
     * @return the value of xd_geography_records.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.create_time
     *
     * @param createTime the value for xd_geography_records.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.update_user_id
     *
     * @return the value of xd_geography_records.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.update_user_id
     *
     * @param updateUserId the value for xd_geography_records.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.update_time
     *
     * @return the value of xd_geography_records.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.update_time
     *
     * @param updateTime the value for xd_geography_records.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_geography_records.del_flag
     *
     * @return the value of xd_geography_records.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_geography_records.del_flag
     *
     * @param delFlag the value for xd_geography_records.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    public Long getLocDate() {
        return locDate;
    }

    public void setLocDate(Long locDate) {
        this.locDate = locDate;
    }
}