package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 公共库资源显示实体
 */
public class XdIsDisplay {
    /** 主键id */
    private String id;

    /** 资源id */
    private String resourcesId;

    /** 所属商务id */
    private String commerceId;

    /** 截止时间 */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_is_display.id
     *
     * @return the value of xd_is_display.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_is_display.id
     *
     * @param id the value for xd_is_display.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_is_display.resources_id
     *
     * @return the value of xd_is_display.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_is_display.resources_id
     *
     * @param resourcesId the value for xd_is_display.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_is_display.commerce_id
     *
     * @return the value of xd_is_display.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_is_display.commerce_id
     *
     * @param commerceId the value for xd_is_display.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_is_display.end_time
     *
     * @return the value of xd_is_display.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_is_display.end_time
     *
     * @param endTime the value for xd_is_display.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}