package net.dgg.cloud.entity;

import java.util.Date;

public class XdOnTime {
    /** 主键id */
    private String onId;

    /** 商务ID */
    private String salesmanId;

    /** 在线时间 */
    private Date onTime;

    /** 离线时间 */
    private Date offTime;

    /** 时长 */
    private Long timeLength;

    /** 0：离线，1：在线，2：繁忙 */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_on_time.on_id
     *
     * @return the value of xd_on_time.on_id
     *
     * @mbggenerated
     */
    public String getOnId() {
        return onId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_on_time.on_id
     *
     * @param onId the value for xd_on_time.on_id
     *
     * @mbggenerated
     */
    public void setOnId(String onId) {
        this.onId = onId == null ? null : onId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_on_time.salesman_id
     *
     * @return the value of xd_on_time.salesman_id
     *
     * @mbggenerated
     */
    public String getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_on_time.salesman_id
     *
     * @param salesmanId the value for xd_on_time.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(String salesmanId) {
        this.salesmanId = salesmanId == null ? null : salesmanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_on_time.on_time
     *
     * @return the value of xd_on_time.on_time
     *
     * @mbggenerated
     */
    public Date getOnTime() {
        return onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_on_time.on_time
     *
     * @param onTime the value for xd_on_time.on_time
     *
     * @mbggenerated
     */
    public void setOnTime(Date onTime) {
        this.onTime = onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_on_time.off_time
     *
     * @return the value of xd_on_time.off_time
     *
     * @mbggenerated
     */
    public Date getOffTime() {
        return offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_on_time.off_time
     *
     * @param offTime the value for xd_on_time.off_time
     *
     * @mbggenerated
     */
    public void setOffTime(Date offTime) {
        this.offTime = offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_on_time.time_length
     *
     * @return the value of xd_on_time.time_length
     *
     * @mbggenerated
     */
    public Long getTimeLength() {
        return timeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_on_time.time_length
     *
     * @param timeLength the value for xd_on_time.time_length
     *
     * @mbggenerated
     */
    public void setTimeLength(Long timeLength) {
        this.timeLength = timeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_on_time.state
     *
     * @return the value of xd_on_time.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_on_time.state
     *
     * @param state the value for xd_on_time.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}