package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 资源接单拒单记录实体
 */
public class XdOrderRecord {
    /** 主键id */
    private String id;

    /** 资源id */
    private String resourcesId;

    /** 所属商务id */
    private String commerceId;

    /** 创建人id */
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    private String updateUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 删除标识(0未删除，1删除) */
    private Integer delFlag;

    /** 接接单拒单（1接单，2拒单,3未响应,4 抢单） */
    private Integer isType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.id
     *
     * @return the value of xd_order_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.id
     *
     * @param id the value for xd_order_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.resources_id
     *
     * @return the value of xd_order_record.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.resources_id
     *
     * @param resourcesId the value for xd_order_record.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.commerce_id
     *
     * @return the value of xd_order_record.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.commerce_id
     *
     * @param commerceId the value for xd_order_record.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.create_user_id
     *
     * @return the value of xd_order_record.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.create_user_id
     *
     * @param createUserId the value for xd_order_record.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.create_time
     *
     * @return the value of xd_order_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.create_time
     *
     * @param createTime the value for xd_order_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.update_user_id
     *
     * @return the value of xd_order_record.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.update_user_id
     *
     * @param updateUserId the value for xd_order_record.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.update_time
     *
     * @return the value of xd_order_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.update_time
     *
     * @param updateTime the value for xd_order_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.del_flag
     *
     * @return the value of xd_order_record.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.del_flag
     *
     * @param delFlag the value for xd_order_record.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_record.is_type
     *
     * @return the value of xd_order_record.is_type
     *
     * @mbggenerated
     */
    public Integer getIsType() {
        return isType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_record.is_type
     *
     * @param isType the value for xd_order_record.is_type
     *
     * @mbggenerated
     */
    public void setIsType(Integer isType) {
        this.isType = isType;
    }
}