package net.dgg.cloud.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

/**
 *
 * @author
 */
public class XdOrderNode {
    /** 节点id */
    private String id;

    /** 订单id */
    private String orderId;

    /** 生产业务id */
    private String processId;

    /** 节点名称 */
    private String processName;

    /** 创建人id */
    @JsonIgnore
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    @JsonIgnore
    private String updateUserId;

    /** 修改时间 */
    @JsonIgnore
    private Date updateTime;

    /** 删除标识(0未删除，1删除) */
    @JsonIgnore
    private Integer delFlag;

    /** 生产节点进度情况 */
    private String preText;

    /** 创建人姓名 */
    private String createUsername;

    /** 创建人工号 */
    @JsonIgnore
    private String createUserNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.id
     *
     * @return the value of xd_order_node.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.id
     *
     * @param id the value for xd_order_node.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.order_id
     *
     * @return the value of xd_order_node.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.order_id
     *
     * @param orderId the value for xd_order_node.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.process_id
     *
     * @return the value of xd_order_node.process_id
     *
     * @mbggenerated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.process_id
     *
     * @param processId the value for xd_order_node.process_id
     *
     * @mbggenerated
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.process_name
     *
     * @return the value of xd_order_node.process_name
     *
     * @mbggenerated
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.process_name
     *
     * @param processName the value for xd_order_node.process_name
     *
     * @mbggenerated
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.create_user_id
     *
     * @return the value of xd_order_node.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.create_user_id
     *
     * @param createUserId the value for xd_order_node.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.create_time
     *
     * @return the value of xd_order_node.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.create_time
     *
     * @param createTime the value for xd_order_node.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.update_user_id
     *
     * @return the value of xd_order_node.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.update_user_id
     *
     * @param updateUserId the value for xd_order_node.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.update_time
     *
     * @return the value of xd_order_node.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.update_time
     *
     * @param updateTime the value for xd_order_node.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.del_flag
     *
     * @return the value of xd_order_node.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.del_flag
     *
     * @param delFlag the value for xd_order_node.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.pre_text
     *
     * @return the value of xd_order_node.pre_text
     *
     * @mbggenerated
     */
    public String getPreText() {
        return preText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.pre_text
     *
     * @param preText the value for xd_order_node.pre_text
     *
     * @mbggenerated
     */
    public void setPreText(String preText) {
        this.preText = preText == null ? null : preText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.create_username
     *
     * @return the value of xd_order_node.create_username
     *
     * @mbggenerated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.create_username
     *
     * @param createUsername the value for xd_order_node.create_username
     *
     * @mbggenerated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_order_node.create_user_no
     *
     * @return the value of xd_order_node.create_user_no
     *
     * @mbggenerated
     */
    public String getCreateUserNo() {
        return createUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_order_node.create_user_no
     *
     * @param createUserNo the value for xd_order_node.create_user_no
     *
     * @mbggenerated
     */
    public void setCreateUserNo(String createUserNo) {
        this.createUserNo = createUserNo == null ? null : createUserNo.trim();
    }
}