package net.dgg.cloud.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.List;

/**
 * 生产订单实体
 * @author
 */
public class XdProductOrder {
    /** 主键id */
    private String id;

    /** 资源id */
    private String resourcesId;

    /** 商机号 */
    private String businessCode;

    /** 生产编号 */
    private String code;

    /** 产品名称(多个产品名称用逗号隔开) */
    private String name;

    /** 订单金额 */
    private Integer price;

    /** 创建人id */
    @JsonIgnore
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    @JsonIgnore
    private String updateUserId;

    /** 修改时间 */
    @JsonIgnore
    private Date updateTime;

    /** 删除标识(0未删除，1删除) */
    @JsonIgnore
    private Integer delFlag;

    /** 生产业务id */
    private String typeId;

    /** 备注 */
    private String cmt;

    private String salesmanId;

    private List<XdOrderNode> orderNode;

    public String getSalesmanId() {
        return salesmanId;
    }

    public void setSalesmanId(String salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.id
     *
     * @return the value of xd_product_order.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.id
     *
     * @param id the value for xd_product_order.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.resources_id
     *
     * @return the value of xd_product_order.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.resources_id
     *
     * @param resourcesId the value for xd_product_order.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.business_code
     *
     * @return the value of xd_product_order.business_code
     *
     * @mbggenerated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.business_code
     *
     * @param businessCode the value for xd_product_order.business_code
     *
     * @mbggenerated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.code
     *
     * @return the value of xd_product_order.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.code
     *
     * @param code the value for xd_product_order.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.name
     *
     * @return the value of xd_product_order.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.name
     *
     * @param name the value for xd_product_order.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.price
     *
     * @return the value of xd_product_order.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.price
     *
     * @param price the value for xd_product_order.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.create_user_id
     *
     * @return the value of xd_product_order.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.create_user_id
     *
     * @param createUserId the value for xd_product_order.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.create_time
     *
     * @return the value of xd_product_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.create_time
     *
     * @param createTime the value for xd_product_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.update_user_id
     *
     * @return the value of xd_product_order.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.update_user_id
     *
     * @param updateUserId the value for xd_product_order.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.update_time
     *
     * @return the value of xd_product_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.update_time
     *
     * @param updateTime the value for xd_product_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.del_flag
     *
     * @return the value of xd_product_order.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.del_flag
     *
     * @param delFlag the value for xd_product_order.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.type_id
     *
     * @return the value of xd_product_order.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.type_id
     *
     * @param typeId the value for xd_product_order.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_product_order.cmt
     *
     * @return the value of xd_product_order.cmt
     *
     * @mbggenerated
     */
    public String getCmt() {
        return cmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_product_order.cmt
     *
     * @param cmt the value for xd_product_order.cmt
     *
     * @mbggenerated
     */
    public void setCmt(String cmt) {
        this.cmt = cmt == null ? null : cmt.trim();
    }

    public List<XdOrderNode> getOrderNode() {
        return orderNode;
    }

    public void setOrderNode(List<XdOrderNode> orderNode) {
        this.orderNode = orderNode;
    }
}