package net.dgg.cloud.entity;

import java.util.Date;

public class XdResourceOperation {
    /** 操作记录主键id */
    private String id;

    /** 资源id */
    private String resourcesId;

    /** 操作人id */
    private String commerceId;

    /** 操作行为 */
    private String operationRecords;

    /** 操作时间 */
    private Date operatingTime;

    /** 操作人名 */
    private String operatorName;

    /** 操作人登录名 */
    private String operatorLoginName;

    /** 录音地址 */
    private String recordUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.id
     *
     * @return the value of xd_resource_operation.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.id
     *
     * @param id the value for xd_resource_operation.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.resources_id
     *
     * @return the value of xd_resource_operation.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.resources_id
     *
     * @param resourcesId the value for xd_resource_operation.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.commerce_id
     *
     * @return the value of xd_resource_operation.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.commerce_id
     *
     * @param commerceId the value for xd_resource_operation.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.operation_records
     *
     * @return the value of xd_resource_operation.operation_records
     *
     * @mbggenerated
     */
    public String getOperationRecords() {
        return operationRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.operation_records
     *
     * @param operationRecords the value for xd_resource_operation.operation_records
     *
     * @mbggenerated
     */
    public void setOperationRecords(String operationRecords) {
        this.operationRecords = operationRecords == null ? null : operationRecords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.operating_time
     *
     * @return the value of xd_resource_operation.operating_time
     *
     * @mbggenerated
     */
    public Date getOperatingTime() {
        return operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.operating_time
     *
     * @param operatingTime the value for xd_resource_operation.operating_time
     *
     * @mbggenerated
     */
    public void setOperatingTime(Date operatingTime) {
        this.operatingTime = operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.operator_name
     *
     * @return the value of xd_resource_operation.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.operator_name
     *
     * @param operatorName the value for xd_resource_operation.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.operator_login_name
     *
     * @return the value of xd_resource_operation.operator_login_name
     *
     * @mbggenerated
     */
    public String getOperatorLoginName() {
        return operatorLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.operator_login_name
     *
     * @param operatorLoginName the value for xd_resource_operation.operator_login_name
     *
     * @mbggenerated
     */
    public void setOperatorLoginName(String operatorLoginName) {
        this.operatorLoginName = operatorLoginName == null ? null : operatorLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_operation.record_url
     *
     * @return the value of xd_resource_operation.record_url
     *
     * @mbggenerated
     */
    public String getRecordUrl() {
        return recordUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_operation.record_url
     *
     * @param recordUrl the value for xd_resource_operation.record_url
     *
     * @mbggenerated
     */
    public void setRecordUrl(String recordUrl) {
        this.recordUrl = recordUrl == null ? null : recordUrl.trim();
    }
}