package net.dgg.cloud.entity;

import java.util.Date;

public class XdResourcesBase {
    /** 资源id */
    private String resourcesId;

    /** 商机号 */
    private String businessCode;

    /** 客户名称 */
    private String customerName;

    /** 客户电话 */
    private String customerPhone;

    /** 客户性别（0待定，1男，2女） */
    private Integer customerSex;

    /** 一级业态名 */
    private String bigBizId;

    /** 业务信息 */
    private String operationTypeId;

    /** 省 */
    private String province;

    /** 上门城市 */
    private String visitCity;

    /** 客户当前定位地址 */
    private String customerAddress;

    /** 上门地址 */
    private String visitAddress;

    /** 咨询时间 */
    private Date consultingTime;

    /** 预约上门时间 */
    private Date subscribeTime;

    /** 客户留言 */
    private String message;

    /** 备注 */
    private String cmt;

    /** 资源来源（0分配，1抢单） */
    private Integer resourceChannel;

    /** 资源状态(0待分配，1待跟进，2跟进中，3已上门，4已成单，5已下单，6公共库，7无效库,8待接收,9:分配中) */
    private Integer resourcesStatus;

    /** 掉入公共库时间 */
    private Date lostTime;

    /** 公共库类型（0剔除，1离职，2拒单，3掉库） */
    private Integer lostType;

    /** 公共库状态（0隐藏，1显示） */
    private Integer lostState;

    /** 公共库显示时间 */
    private Date lostDisplayTime;

    /** 公共库掉入人 */
    private String lostUserId;

    /** 申请无效次数 */
    private Integer invalidNum;

    /** 申请无效时间 */
    private Date invalidTime;

    /** 申请无效原因 */
    private String reason;

    /** 下单时间 */
    private Date placeTime;

    /** 成单时间 */
    private Date fOrderTime;

    /** 分配人 */
    private String assignerUserId;

    /** 分配人名 */
    private String assignerUserName;

    /** 分配人工号 */
    private String assignerUserWorkno;

    /** 分配时间 */
    private Date assignerTime;

    /** 预计返回待分配时间（20分钟未响应--该字段弃用） */
    private Date esReTime;

    /** 下次跟进时间(掉库时间) */
    private Date nextFollowTime;

    /** 接单人 */
    private String firstUserId;

    /** 接单时间 */
    private Date firstTime;

    /** 资源成本 */
    private Integer resourcesCost;

    /** 是否计算成本,0：不计算，1：计算 */
    private Integer isCost;

    /** 所属商务id */
    private String commerceId;

    /** 创建人id */
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    private String updateUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 删除标识(0未删除，1删除) */
    private Integer delFlag;

    /** 是否推送语音(0未推送，1推送) */
    private Integer isPush;

    /** 无效来源（0跟进中，1已上门） */
    private Integer invalidSource;

    /** 经度 */
    private String longitude;

    /** 纬度 */
    private String latitude;

    /** 来源渠道(0后台录入，1资源中心录入，2微信端录入)，20180619二期被res_source_id取代 */
    private Integer channelSource;

    /** 订单操作人姓名 */
    private String orderOpName;

    /** 订单操作人工号 */
    private String orderOpNumber;

    /** 资源渠道id */
    private String resSourceId;

    /** 自动分配次数 */
    private Integer autoDisNum;

    /** 外部商机号 */
    private String extBusinessCode;

    /** 当前上门记录id，如果不为空且非空字符串时表示正在上门中 */
    private String currentVisitId;

    /** 最新跟进时间 */
    private Date lastFollowTime;

    /** 最新上门时间 */
    private Date lastVisitTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.resources_id
     *
     * @return the value of xd_resources_base.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.resources_id
     *
     * @param resourcesId the value for xd_resources_base.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.business_code
     *
     * @return the value of xd_resources_base.business_code
     *
     * @mbggenerated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.business_code
     *
     * @param businessCode the value for xd_resources_base.business_code
     *
     * @mbggenerated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.customer_name
     *
     * @return the value of xd_resources_base.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.customer_name
     *
     * @param customerName the value for xd_resources_base.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.customer_phone
     *
     * @return the value of xd_resources_base.customer_phone
     *
     * @mbggenerated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.customer_phone
     *
     * @param customerPhone the value for xd_resources_base.customer_phone
     *
     * @mbggenerated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.customer_sex
     *
     * @return the value of xd_resources_base.customer_sex
     *
     * @mbggenerated
     */
    public Integer getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.customer_sex
     *
     * @param customerSex the value for xd_resources_base.customer_sex
     *
     * @mbggenerated
     */
    public void setCustomerSex(Integer customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.big_biz_id
     *
     * @return the value of xd_resources_base.big_biz_id
     *
     * @mbggenerated
     */
    public String getBigBizId() {
        return bigBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.big_biz_id
     *
     * @param bigBizId the value for xd_resources_base.big_biz_id
     *
     * @mbggenerated
     */
    public void setBigBizId(String bigBizId) {
        this.bigBizId = bigBizId == null ? null : bigBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.operation_type_id
     *
     * @return the value of xd_resources_base.operation_type_id
     *
     * @mbggenerated
     */
    public String getOperationTypeId() {
        return operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.operation_type_id
     *
     * @param operationTypeId the value for xd_resources_base.operation_type_id
     *
     * @mbggenerated
     */
    public void setOperationTypeId(String operationTypeId) {
        this.operationTypeId = operationTypeId == null ? null : operationTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.province
     *
     * @return the value of xd_resources_base.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.province
     *
     * @param province the value for xd_resources_base.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.visit_city
     *
     * @return the value of xd_resources_base.visit_city
     *
     * @mbggenerated
     */
    public String getVisitCity() {
        return visitCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.visit_city
     *
     * @param visitCity the value for xd_resources_base.visit_city
     *
     * @mbggenerated
     */
    public void setVisitCity(String visitCity) {
        this.visitCity = visitCity == null ? null : visitCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.customer_address
     *
     * @return the value of xd_resources_base.customer_address
     *
     * @mbggenerated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.customer_address
     *
     * @param customerAddress the value for xd_resources_base.customer_address
     *
     * @mbggenerated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.visit_address
     *
     * @return the value of xd_resources_base.visit_address
     *
     * @mbggenerated
     */
    public String getVisitAddress() {
        return visitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.visit_address
     *
     * @param visitAddress the value for xd_resources_base.visit_address
     *
     * @mbggenerated
     */
    public void setVisitAddress(String visitAddress) {
        this.visitAddress = visitAddress == null ? null : visitAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.consulting_time
     *
     * @return the value of xd_resources_base.consulting_time
     *
     * @mbggenerated
     */
    public Date getConsultingTime() {
        return consultingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.consulting_time
     *
     * @param consultingTime the value for xd_resources_base.consulting_time
     *
     * @mbggenerated
     */
    public void setConsultingTime(Date consultingTime) {
        this.consultingTime = consultingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.subscribe_time
     *
     * @return the value of xd_resources_base.subscribe_time
     *
     * @mbggenerated
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.subscribe_time
     *
     * @param subscribeTime the value for xd_resources_base.subscribe_time
     *
     * @mbggenerated
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.message
     *
     * @return the value of xd_resources_base.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.message
     *
     * @param message the value for xd_resources_base.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.cmt
     *
     * @return the value of xd_resources_base.cmt
     *
     * @mbggenerated
     */
    public String getCmt() {
        return cmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.cmt
     *
     * @param cmt the value for xd_resources_base.cmt
     *
     * @mbggenerated
     */
    public void setCmt(String cmt) {
        this.cmt = cmt == null ? null : cmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.resource_channel
     *
     * @return the value of xd_resources_base.resource_channel
     *
     * @mbggenerated
     */
    public Integer getResourceChannel() {
        return resourceChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.resource_channel
     *
     * @param resourceChannel the value for xd_resources_base.resource_channel
     *
     * @mbggenerated
     */
    public void setResourceChannel(Integer resourceChannel) {
        this.resourceChannel = resourceChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.resources_status
     *
     * @return the value of xd_resources_base.resources_status
     *
     * @mbggenerated
     */
    public Integer getResourcesStatus() {
        return resourcesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.resources_status
     *
     * @param resourcesStatus the value for xd_resources_base.resources_status
     *
     * @mbggenerated
     */
    public void setResourcesStatus(Integer resourcesStatus) {
        this.resourcesStatus = resourcesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.lost_time
     *
     * @return the value of xd_resources_base.lost_time
     *
     * @mbggenerated
     */
    public Date getLostTime() {
        return lostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.lost_time
     *
     * @param lostTime the value for xd_resources_base.lost_time
     *
     * @mbggenerated
     */
    public void setLostTime(Date lostTime) {
        this.lostTime = lostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.lost_type
     *
     * @return the value of xd_resources_base.lost_type
     *
     * @mbggenerated
     */
    public Integer getLostType() {
        return lostType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.lost_type
     *
     * @param lostType the value for xd_resources_base.lost_type
     *
     * @mbggenerated
     */
    public void setLostType(Integer lostType) {
        this.lostType = lostType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.lost_state
     *
     * @return the value of xd_resources_base.lost_state
     *
     * @mbggenerated
     */
    public Integer getLostState() {
        return lostState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.lost_state
     *
     * @param lostState the value for xd_resources_base.lost_state
     *
     * @mbggenerated
     */
    public void setLostState(Integer lostState) {
        this.lostState = lostState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.lost_display_time
     *
     * @return the value of xd_resources_base.lost_display_time
     *
     * @mbggenerated
     */
    public Date getLostDisplayTime() {
        return lostDisplayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.lost_display_time
     *
     * @param lostDisplayTime the value for xd_resources_base.lost_display_time
     *
     * @mbggenerated
     */
    public void setLostDisplayTime(Date lostDisplayTime) {
        this.lostDisplayTime = lostDisplayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.lost_user_id
     *
     * @return the value of xd_resources_base.lost_user_id
     *
     * @mbggenerated
     */
    public String getLostUserId() {
        return lostUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.lost_user_id
     *
     * @param lostUserId the value for xd_resources_base.lost_user_id
     *
     * @mbggenerated
     */
    public void setLostUserId(String lostUserId) {
        this.lostUserId = lostUserId == null ? null : lostUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.invalid_num
     *
     * @return the value of xd_resources_base.invalid_num
     *
     * @mbggenerated
     */
    public Integer getInvalidNum() {
        return invalidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.invalid_num
     *
     * @param invalidNum the value for xd_resources_base.invalid_num
     *
     * @mbggenerated
     */
    public void setInvalidNum(Integer invalidNum) {
        this.invalidNum = invalidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.invalid_time
     *
     * @return the value of xd_resources_base.invalid_time
     *
     * @mbggenerated
     */
    public Date getInvalidTime() {
        return invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.invalid_time
     *
     * @param invalidTime the value for xd_resources_base.invalid_time
     *
     * @mbggenerated
     */
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.reason
     *
     * @return the value of xd_resources_base.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.reason
     *
     * @param reason the value for xd_resources_base.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.place_time
     *
     * @return the value of xd_resources_base.place_time
     *
     * @mbggenerated
     */
    public Date getPlaceTime() {
        return placeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.place_time
     *
     * @param placeTime the value for xd_resources_base.place_time
     *
     * @mbggenerated
     */
    public void setPlaceTime(Date placeTime) {
        this.placeTime = placeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.f_order_time
     *
     * @return the value of xd_resources_base.f_order_time
     *
     * @mbggenerated
     */
    public Date getfOrderTime() {
        return fOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.f_order_time
     *
     * @param fOrderTime the value for xd_resources_base.f_order_time
     *
     * @mbggenerated
     */
    public void setfOrderTime(Date fOrderTime) {
        this.fOrderTime = fOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.assigner_user_id
     *
     * @return the value of xd_resources_base.assigner_user_id
     *
     * @mbggenerated
     */
    public String getAssignerUserId() {
        return assignerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.assigner_user_id
     *
     * @param assignerUserId the value for xd_resources_base.assigner_user_id
     *
     * @mbggenerated
     */
    public void setAssignerUserId(String assignerUserId) {
        this.assignerUserId = assignerUserId == null ? null : assignerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.assigner_user_name
     *
     * @return the value of xd_resources_base.assigner_user_name
     *
     * @mbggenerated
     */
    public String getAssignerUserName() {
        return assignerUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.assigner_user_name
     *
     * @param assignerUserName the value for xd_resources_base.assigner_user_name
     *
     * @mbggenerated
     */
    public void setAssignerUserName(String assignerUserName) {
        this.assignerUserName = assignerUserName == null ? null : assignerUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.assigner_user_workno
     *
     * @return the value of xd_resources_base.assigner_user_workno
     *
     * @mbggenerated
     */
    public String getAssignerUserWorkno() {
        return assignerUserWorkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.assigner_user_workno
     *
     * @param assignerUserWorkno the value for xd_resources_base.assigner_user_workno
     *
     * @mbggenerated
     */
    public void setAssignerUserWorkno(String assignerUserWorkno) {
        this.assignerUserWorkno = assignerUserWorkno == null ? null : assignerUserWorkno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.assigner_time
     *
     * @return the value of xd_resources_base.assigner_time
     *
     * @mbggenerated
     */
    public Date getAssignerTime() {
        return assignerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.assigner_time
     *
     * @param assignerTime the value for xd_resources_base.assigner_time
     *
     * @mbggenerated
     */
    public void setAssignerTime(Date assignerTime) {
        this.assignerTime = assignerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.es_re_time
     *
     * @return the value of xd_resources_base.es_re_time
     *
     * @mbggenerated
     */
    public Date getEsReTime() {
        return esReTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.es_re_time
     *
     * @param esReTime the value for xd_resources_base.es_re_time
     *
     * @mbggenerated
     */
    public void setEsReTime(Date esReTime) {
        this.esReTime = esReTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.next_follow_time
     *
     * @return the value of xd_resources_base.next_follow_time
     *
     * @mbggenerated
     */
    public Date getNextFollowTime() {
        return nextFollowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.next_follow_time
     *
     * @param nextFollowTime the value for xd_resources_base.next_follow_time
     *
     * @mbggenerated
     */
    public void setNextFollowTime(Date nextFollowTime) {
        this.nextFollowTime = nextFollowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.first_user_id
     *
     * @return the value of xd_resources_base.first_user_id
     *
     * @mbggenerated
     */
    public String getFirstUserId() {
        return firstUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.first_user_id
     *
     * @param firstUserId the value for xd_resources_base.first_user_id
     *
     * @mbggenerated
     */
    public void setFirstUserId(String firstUserId) {
        this.firstUserId = firstUserId == null ? null : firstUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.first_time
     *
     * @return the value of xd_resources_base.first_time
     *
     * @mbggenerated
     */
    public Date getFirstTime() {
        return firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.first_time
     *
     * @param firstTime the value for xd_resources_base.first_time
     *
     * @mbggenerated
     */
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.resources_cost
     *
     * @return the value of xd_resources_base.resources_cost
     *
     * @mbggenerated
     */
    public Integer getResourcesCost() {
        return resourcesCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.resources_cost
     *
     * @param resourcesCost the value for xd_resources_base.resources_cost
     *
     * @mbggenerated
     */
    public void setResourcesCost(Integer resourcesCost) {
        this.resourcesCost = resourcesCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.is_cost
     *
     * @return the value of xd_resources_base.is_cost
     *
     * @mbggenerated
     */
    public Integer getIsCost() {
        return isCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.is_cost
     *
     * @param isCost the value for xd_resources_base.is_cost
     *
     * @mbggenerated
     */
    public void setIsCost(Integer isCost) {
        this.isCost = isCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.commerce_id
     *
     * @return the value of xd_resources_base.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.commerce_id
     *
     * @param commerceId the value for xd_resources_base.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.create_user_id
     *
     * @return the value of xd_resources_base.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.create_user_id
     *
     * @param createUserId the value for xd_resources_base.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.create_time
     *
     * @return the value of xd_resources_base.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.create_time
     *
     * @param createTime the value for xd_resources_base.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.update_user_id
     *
     * @return the value of xd_resources_base.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.update_user_id
     *
     * @param updateUserId the value for xd_resources_base.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.update_time
     *
     * @return the value of xd_resources_base.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.update_time
     *
     * @param updateTime the value for xd_resources_base.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.del_flag
     *
     * @return the value of xd_resources_base.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.del_flag
     *
     * @param delFlag the value for xd_resources_base.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.is_push
     *
     * @return the value of xd_resources_base.is_push
     *
     * @mbggenerated
     */
    public Integer getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.is_push
     *
     * @param isPush the value for xd_resources_base.is_push
     *
     * @mbggenerated
     */
    public void setIsPush(Integer isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.invalid_source
     *
     * @return the value of xd_resources_base.invalid_source
     *
     * @mbggenerated
     */
    public Integer getInvalidSource() {
        return invalidSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.invalid_source
     *
     * @param invalidSource the value for xd_resources_base.invalid_source
     *
     * @mbggenerated
     */
    public void setInvalidSource(Integer invalidSource) {
        this.invalidSource = invalidSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.longitude
     *
     * @return the value of xd_resources_base.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.longitude
     *
     * @param longitude the value for xd_resources_base.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.latitude
     *
     * @return the value of xd_resources_base.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.latitude
     *
     * @param latitude the value for xd_resources_base.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.channel_source
     *
     * @return the value of xd_resources_base.channel_source
     *
     * @mbggenerated
     */
    public Integer getChannelSource() {
        return channelSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.channel_source
     *
     * @param channelSource the value for xd_resources_base.channel_source
     *
     * @mbggenerated
     */
    public void setChannelSource(Integer channelSource) {
        this.channelSource = channelSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.order_op_name
     *
     * @return the value of xd_resources_base.order_op_name
     *
     * @mbggenerated
     */
    public String getOrderOpName() {
        return orderOpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.order_op_name
     *
     * @param orderOpName the value for xd_resources_base.order_op_name
     *
     * @mbggenerated
     */
    public void setOrderOpName(String orderOpName) {
        this.orderOpName = orderOpName == null ? null : orderOpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.order_op_number
     *
     * @return the value of xd_resources_base.order_op_number
     *
     * @mbggenerated
     */
    public String getOrderOpNumber() {
        return orderOpNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.order_op_number
     *
     * @param orderOpNumber the value for xd_resources_base.order_op_number
     *
     * @mbggenerated
     */
    public void setOrderOpNumber(String orderOpNumber) {
        this.orderOpNumber = orderOpNumber == null ? null : orderOpNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.res_source_id
     *
     * @return the value of xd_resources_base.res_source_id
     *
     * @mbggenerated
     */
    public String getResSourceId() {
        return resSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.res_source_id
     *
     * @param resSourceId the value for xd_resources_base.res_source_id
     *
     * @mbggenerated
     */
    public void setResSourceId(String resSourceId) {
        this.resSourceId = resSourceId == null ? null : resSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.auto_dis_num
     *
     * @return the value of xd_resources_base.auto_dis_num
     *
     * @mbggenerated
     */
    public Integer getAutoDisNum() {
        return autoDisNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.auto_dis_num
     *
     * @param autoDisNum the value for xd_resources_base.auto_dis_num
     *
     * @mbggenerated
     */
    public void setAutoDisNum(Integer autoDisNum) {
        this.autoDisNum = autoDisNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.ext_business_code
     *
     * @return the value of xd_resources_base.ext_business_code
     *
     * @mbggenerated
     */
    public String getExtBusinessCode() {
        return extBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.ext_business_code
     *
     * @param extBusinessCode the value for xd_resources_base.ext_business_code
     *
     * @mbggenerated
     */
    public void setExtBusinessCode(String extBusinessCode) {
        this.extBusinessCode = extBusinessCode == null ? null : extBusinessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.current_visit_id
     *
     * @return the value of xd_resources_base.current_visit_id
     *
     * @mbggenerated
     */
    public String getCurrentVisitId() {
        return currentVisitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.current_visit_id
     *
     * @param currentVisitId the value for xd_resources_base.current_visit_id
     *
     * @mbggenerated
     */
    public void setCurrentVisitId(String currentVisitId) {
        this.currentVisitId = currentVisitId == null ? null : currentVisitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.last_follow_time
     *
     * @return the value of xd_resources_base.last_follow_time
     *
     * @mbggenerated
     */
    public Date getLastFollowTime() {
        return lastFollowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.last_follow_time
     *
     * @param lastFollowTime the value for xd_resources_base.last_follow_time
     *
     * @mbggenerated
     */
    public void setLastFollowTime(Date lastFollowTime) {
        this.lastFollowTime = lastFollowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_base.last_visit_time
     *
     * @return the value of xd_resources_base.last_visit_time
     *
     * @mbggenerated
     */
    public Date getLastVisitTime() {
        return lastVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_base.last_visit_time
     *
     * @param lastVisitTime the value for xd_resources_base.last_visit_time
     *
     * @mbggenerated
     */
    public void setLastVisitTime(Date lastVisitTime) {
        this.lastVisitTime = lastVisitTime;
    }
}