package net.dgg.cloud.entity;

import java.util.Date;

public class XdResourceDistribution {
    /** 分配记录表主键id */
    private String distributionId;

    /** 资源id */
    private String resourcesId;

    /** 分配人id */
    private String assignorId;

    /** 分配人姓名 */
    private String assignorName;

    /** 分配人工号 */
    private String assignorWorkno;

    /** 被分配人id */
    private String commerceId;

    /** 分配时间 */
    private Date disTime;

    /** 响应状态，0：已分配，1：接单，2：未响应，3：拒单 */
    private Integer responseFlag;

    /** 响应时间 */
    private Date responseTime;

    /** 分配类型，0：手动分配，1：自动分配 */
    private Integer disType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.distribution_id
     *
     * @return the value of xd_resource_distribution.distribution_id
     *
     * @mbggenerated
     */
    public String getDistributionId() {
        return distributionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.distribution_id
     *
     * @param distributionId the value for xd_resource_distribution.distribution_id
     *
     * @mbggenerated
     */
    public void setDistributionId(String distributionId) {
        this.distributionId = distributionId == null ? null : distributionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.resources_id
     *
     * @return the value of xd_resource_distribution.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.resources_id
     *
     * @param resourcesId the value for xd_resource_distribution.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.assignor_id
     *
     * @return the value of xd_resource_distribution.assignor_id
     *
     * @mbggenerated
     */
    public String getAssignorId() {
        return assignorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.assignor_id
     *
     * @param assignorId the value for xd_resource_distribution.assignor_id
     *
     * @mbggenerated
     */
    public void setAssignorId(String assignorId) {
        this.assignorId = assignorId == null ? null : assignorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.assignor_name
     *
     * @return the value of xd_resource_distribution.assignor_name
     *
     * @mbggenerated
     */
    public String getAssignorName() {
        return assignorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.assignor_name
     *
     * @param assignorName the value for xd_resource_distribution.assignor_name
     *
     * @mbggenerated
     */
    public void setAssignorName(String assignorName) {
        this.assignorName = assignorName == null ? null : assignorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.assignor_workno
     *
     * @return the value of xd_resource_distribution.assignor_workno
     *
     * @mbggenerated
     */
    public String getAssignorWorkno() {
        return assignorWorkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.assignor_workno
     *
     * @param assignorWorkno the value for xd_resource_distribution.assignor_workno
     *
     * @mbggenerated
     */
    public void setAssignorWorkno(String assignorWorkno) {
        this.assignorWorkno = assignorWorkno == null ? null : assignorWorkno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.commerce_id
     *
     * @return the value of xd_resource_distribution.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.commerce_id
     *
     * @param commerceId the value for xd_resource_distribution.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.dis_time
     *
     * @return the value of xd_resource_distribution.dis_time
     *
     * @mbggenerated
     */
    public Date getDisTime() {
        return disTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.dis_time
     *
     * @param disTime the value for xd_resource_distribution.dis_time
     *
     * @mbggenerated
     */
    public void setDisTime(Date disTime) {
        this.disTime = disTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.response_flag
     *
     * @return the value of xd_resource_distribution.response_flag
     *
     * @mbggenerated
     */
    public Integer getResponseFlag() {
        return responseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.response_flag
     *
     * @param responseFlag the value for xd_resource_distribution.response_flag
     *
     * @mbggenerated
     */
    public void setResponseFlag(Integer responseFlag) {
        this.responseFlag = responseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.response_time
     *
     * @return the value of xd_resource_distribution.response_time
     *
     * @mbggenerated
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.response_time
     *
     * @param responseTime the value for xd_resource_distribution.response_time
     *
     * @mbggenerated
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_distribution.dis_type
     *
     * @return the value of xd_resource_distribution.dis_type
     *
     * @mbggenerated
     */
    public Integer getDisType() {
        return disType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_distribution.dis_type
     *
     * @param disType the value for xd_resource_distribution.dis_type
     *
     * @mbggenerated
     */
    public void setDisType(Integer disType) {
        this.disType = disType;
    }
}