package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 资源审核记录实体
 */
public class XdResourceAudit {
    /** 审核记录主键id */
    private String auditId;

    /** 资源id */
    private String resourcesId;

    /** 原因 */
    private String reason;

    /** 所属商务id */
    private String commerceId;

    /** 审核时间 */
    private Date applyTime;

    /** 审核人id */
    private String applyUserId;

    /** 审核结果（0未通过，1通过） */
    private Integer applyRe;
    /** 审核人姓名 */
    private String name;

    /** 审核人工号 */
    private String number;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.audit_id
     *
     * @return the value of xd_resource_audit.audit_id
     *
     * @mbggenerated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.audit_id
     *
     * @param auditId the value for xd_resource_audit.audit_id
     *
     * @mbggenerated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId == null ? null : auditId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.resources_id
     *
     * @return the value of xd_resource_audit.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.resources_id
     *
     * @param resourcesId the value for xd_resource_audit.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.reason
     *
     * @return the value of xd_resource_audit.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.reason
     *
     * @param reason the value for xd_resource_audit.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.commerce_id
     *
     * @return the value of xd_resource_audit.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.commerce_id
     *
     * @param commerceId the value for xd_resource_audit.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.apply_time
     *
     * @return the value of xd_resource_audit.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.apply_time
     *
     * @param applyTime the value for xd_resource_audit.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.apply_user_id
     *
     * @return the value of xd_resource_audit.apply_user_id
     *
     * @mbggenerated
     */
    public String getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.apply_user_id
     *
     * @param applyUserId the value for xd_resource_audit.apply_user_id
     *
     * @mbggenerated
     */
    public void setApplyUserId(String applyUserId) {
        this.applyUserId = applyUserId == null ? null : applyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_audit.apply_re
     *
     * @return the value of xd_resource_audit.apply_re
     *
     * @mbggenerated
     */
    public Integer getApplyRe() {
        return applyRe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_audit.apply_re
     *
     * @param applyRe the value for xd_resource_audit.apply_re
     *
     * @mbggenerated
     */
    public void setApplyRe(Integer applyRe) {
        this.applyRe = applyRe;
    }
}