package net.dgg.cloud.entity;

import java.util.Date;

public class XdResourceSource {
    /** 主键 */
    private String id;

    /** 来源名称 */
    private String sourceName;

    /** 资源渠道编码，是唯一的不可重复 */
    private String sourceCode;

    /** 资源价格，单位元 */
    private Integer sourcePrice;

    /** 删除标记，0：未删除，1：删除 */
    private Integer delFlag;

    /** 创建时间 */
    private Date createTime;

    /** 创建者id */
    private String createUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 修改者id */
    private String updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.id
     *
     * @return the value of xd_resource_source.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.id
     *
     * @param id the value for xd_resource_source.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.source_name
     *
     * @return the value of xd_resource_source.source_name
     *
     * @mbggenerated
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.source_name
     *
     * @param sourceName the value for xd_resource_source.source_name
     *
     * @mbggenerated
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.source_code
     *
     * @return the value of xd_resource_source.source_code
     *
     * @mbggenerated
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.source_code
     *
     * @param sourceCode the value for xd_resource_source.source_code
     *
     * @mbggenerated
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.source_price
     *
     * @return the value of xd_resource_source.source_price
     *
     * @mbggenerated
     */
    public Integer getSourcePrice() {
        return sourcePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.source_price
     *
     * @param sourcePrice the value for xd_resource_source.source_price
     *
     * @mbggenerated
     */
    public void setSourcePrice(Integer sourcePrice) {
        this.sourcePrice = sourcePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.del_flag
     *
     * @return the value of xd_resource_source.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.del_flag
     *
     * @param delFlag the value for xd_resource_source.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.create_time
     *
     * @return the value of xd_resource_source.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.create_time
     *
     * @param createTime the value for xd_resource_source.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.create_user_id
     *
     * @return the value of xd_resource_source.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.create_user_id
     *
     * @param createUserId the value for xd_resource_source.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.update_time
     *
     * @return the value of xd_resource_source.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.update_time
     *
     * @param updateTime the value for xd_resource_source.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_source.update_user_id
     *
     * @return the value of xd_resource_source.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_source.update_user_id
     *
     * @param updateUserId the value for xd_resource_source.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }
}