package net.dgg.cloud.entity;

import java.util.Date;

public class XdResourceVisit {
    /** 上门id */
    private String visitId;

    /** 资源id */
    private String resourcesId;

    /** 上门时间 */
    private Date visitTime;

    /** 上门图片（多个逗号隔开） */
    private String visitImg;

    /** 上门地址 */
    private String visitAddress;

    /** 谈单类型（0标准谈单，1非标准谈单） */
    private Integer talkOrderType;

    /** 谈单情况（0上门，1成单） */
    private Integer talkOrderSituation;

    /** 备注 */
    private String remark;

    /** 商务id */
    private String salesmanId;

    /** 创建时间 */
    private Date createTime;

    /** 上门状态：开始上门1，我已到达2，我已成单3，下次跟进4，取消上门5，无效上门6 */
    private Integer state;

    /** 结束时间 */
    private Date endTime;

    /** 经度 */
    private String longitude;

    /** 纬度 */
    private String latitude;

    /** 是否添加微信：否0，是1 */
    private Integer addWx;

    /** 未添加微信原因 */
    private String notAddWxReason;

    /** 距離(公里數） */
    private Double distance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.visit_id
     *
     * @return the value of xd_resource_visit.visit_id
     *
     * @mbggenerated
     */
    public String getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.visit_id
     *
     * @param visitId the value for xd_resource_visit.visit_id
     *
     * @mbggenerated
     */
    public void setVisitId(String visitId) {
        this.visitId = visitId == null ? null : visitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.resources_id
     *
     * @return the value of xd_resource_visit.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.resources_id
     *
     * @param resourcesId the value for xd_resource_visit.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.visit_time
     *
     * @return the value of xd_resource_visit.visit_time
     *
     * @mbggenerated
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.visit_time
     *
     * @param visitTime the value for xd_resource_visit.visit_time
     *
     * @mbggenerated
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.visit_img
     *
     * @return the value of xd_resource_visit.visit_img
     *
     * @mbggenerated
     */
    public String getVisitImg() {
        return visitImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.visit_img
     *
     * @param visitImg the value for xd_resource_visit.visit_img
     *
     * @mbggenerated
     */
    public void setVisitImg(String visitImg) {
        this.visitImg = visitImg == null ? null : visitImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.visit_address
     *
     * @return the value of xd_resource_visit.visit_address
     *
     * @mbggenerated
     */
    public String getVisitAddress() {
        return visitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.visit_address
     *
     * @param visitAddress the value for xd_resource_visit.visit_address
     *
     * @mbggenerated
     */
    public void setVisitAddress(String visitAddress) {
        this.visitAddress = visitAddress == null ? null : visitAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.talk_order_type
     *
     * @return the value of xd_resource_visit.talk_order_type
     *
     * @mbggenerated
     */
    public Integer getTalkOrderType() {
        return talkOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.talk_order_type
     *
     * @param talkOrderType the value for xd_resource_visit.talk_order_type
     *
     * @mbggenerated
     */
    public void setTalkOrderType(Integer talkOrderType) {
        this.talkOrderType = talkOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.talk_order_situation
     *
     * @return the value of xd_resource_visit.talk_order_situation
     *
     * @mbggenerated
     */
    public Integer getTalkOrderSituation() {
        return talkOrderSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.talk_order_situation
     *
     * @param talkOrderSituation the value for xd_resource_visit.talk_order_situation
     *
     * @mbggenerated
     */
    public void setTalkOrderSituation(Integer talkOrderSituation) {
        this.talkOrderSituation = talkOrderSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.remark
     *
     * @return the value of xd_resource_visit.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.remark
     *
     * @param remark the value for xd_resource_visit.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.salesman_id
     *
     * @return the value of xd_resource_visit.salesman_id
     *
     * @mbggenerated
     */
    public String getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.salesman_id
     *
     * @param salesmanId the value for xd_resource_visit.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(String salesmanId) {
        this.salesmanId = salesmanId == null ? null : salesmanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.create_time
     *
     * @return the value of xd_resource_visit.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.create_time
     *
     * @param createTime the value for xd_resource_visit.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.state
     *
     * @return the value of xd_resource_visit.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.state
     *
     * @param state the value for xd_resource_visit.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.end_time
     *
     * @return the value of xd_resource_visit.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.end_time
     *
     * @param endTime the value for xd_resource_visit.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.longitude
     *
     * @return the value of xd_resource_visit.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.longitude
     *
     * @param longitude the value for xd_resource_visit.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.latitude
     *
     * @return the value of xd_resource_visit.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.latitude
     *
     * @param latitude the value for xd_resource_visit.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.add_wx
     *
     * @return the value of xd_resource_visit.add_wx
     *
     * @mbggenerated
     */
    public Integer getAddWx() {
        return addWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.add_wx
     *
     * @param addWx the value for xd_resource_visit.add_wx
     *
     * @mbggenerated
     */
    public void setAddWx(Integer addWx) {
        this.addWx = addWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.not_add_wx_reason
     *
     * @return the value of xd_resource_visit.not_add_wx_reason
     *
     * @mbggenerated
     */
    public String getNotAddWxReason() {
        return notAddWxReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.not_add_wx_reason
     *
     * @param notAddWxReason the value for xd_resource_visit.not_add_wx_reason
     *
     * @mbggenerated
     */
    public void setNotAddWxReason(String notAddWxReason) {
        this.notAddWxReason = notAddWxReason == null ? null : notAddWxReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_visit.distance
     *
     * @return the value of xd_resource_visit.distance
     *
     * @mbggenerated
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_visit.distance
     *
     * @param distance the value for xd_resource_visit.distance
     *
     * @mbggenerated
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }
}