package net.dgg.cloud.entity;

public class XdResourcesStatus {
    /** 主键id */
    private String id;

    /** 资源状态 */
    private Integer resourceStatus;

    /**状态名称**/
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_status.id
     *
     * @return the value of xd_resources_status.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_status.id
     *
     * @param id the value for xd_resources_status.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resources_status.resource_status
     *
     * @return the value of xd_resources_status.resource_status
     *
     * @mbggenerated
     */
    public Integer getResourceStatus() {
        return resourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resources_status.resource_status
     *
     * @param resourceStatus the value for xd_resources_status.resource_status
     *
     * @mbggenerated
     */
    public void setResourceStatus(Integer resourceStatus) {
        this.resourceStatus = resourceStatus;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
}