package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 资源跟进信息实体
 */
public class XdResourceFollow {
    /** 跟进id */
    private String followId;

    /** 资源id */
    private String resourcesId;

    /** 跟进人 */
    private String commerceId;

    /** 商务名称 */
    private String commerceName;

    /** 备注 */
    private String cmt;

    /** 跟进时间 */
    private Date followTime;


    /** 根据类型（0：骑手根据，1：管理人员跟进） */
    private Integer followType;

    /** 所属人登录名，骑手为手机号，管理人员为工号 */
    private String commerceLoginName;

    public Integer getFollowType() {
        return followType;
    }

    public void setFollowType(Integer followType) {
        this.followType = followType;
    }

    public String getCommerceLoginName() {
        return commerceLoginName;
    }

    public void setCommerceLoginName(String commerceLoginName) {
        this.commerceLoginName = commerceLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_follow.follow_id
     *
     * @return the value of xd_resource_follow.follow_id
     *
     * @mbggenerated
     */
    public String getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_follow.follow_id
     *
     * @param followId the value for xd_resource_follow.follow_id
     *
     * @mbggenerated
     */
    public void setFollowId(String followId) {
        this.followId = followId == null ? null : followId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_follow.resources_id
     *
     * @return the value of xd_resource_follow.resources_id
     *
     * @mbggenerated
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_follow.resources_id
     *
     * @param resourcesId the value for xd_resource_follow.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_follow.commerce_id
     *
     * @return the value of xd_resource_follow.commerce_id
     *
     * @mbggenerated
     */
    public String getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_follow.commerce_id
     *
     * @param commerceId the value for xd_resource_follow.commerce_id
     *
     * @mbggenerated
     */
    public void setCommerceId(String commerceId) {
        this.commerceId = commerceId == null ? null : commerceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_follow.commerce_name
     *
     * @return the value of xd_resource_follow.commerce_name
     *
     * @mbggenerated
     */
    public String getCommerceName() {
        return commerceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_follow.commerce_name
     *
     * @param commerceName the value for xd_resource_follow.commerce_name
     *
     * @mbggenerated
     */
    public void setCommerceName(String commerceName) {
        this.commerceName = commerceName == null ? null : commerceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_follow.cmt
     *
     * @return the value of xd_resource_follow.cmt
     *
     * @mbggenerated
     */
    public String getCmt() {
        return cmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_follow.cmt
     *
     * @param cmt the value for xd_resource_follow.cmt
     *
     * @mbggenerated
     */
    public void setCmt(String cmt) {
        this.cmt = cmt == null ? null : cmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_resource_follow.follow_time
     *
     * @return the value of xd_resource_follow.follow_time
     *
     * @mbggenerated
     */
    public Date getFollowTime() {
        return followTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_resource_follow.follow_time
     *
     * @param followTime the value for xd_resource_follow.follow_time
     *
     * @mbggenerated
     */
    public void setFollowTime(Date followTime) {
        this.followTime = followTime;
    }

}