package net.dgg.cloud.entity;

import java.util.Date;

/**
 * 小顶商务级别实体
 */
public class XdSalesmanGrade {
    /** 主键id */
    private String id;

    /** 级别名称 */
    private String name;

    /** 月资源接收量 */
    private Integer monthOrderNum;

    /** 待处理库容量(不含已签单) */
    private Integer storageNum;

    /** 创建人id */
    private String createUserId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人id */
    private String updateUserId;

    /** 修改时间 */
    private Date updateTime;

    /** 是否删除，0：未删除，1：删除 */
    private Integer isDel;

    /** 是否为默认等级，0：不是，1：是。添加新的小顶商务时若没有指定等级就使用默认等级 */
    private Integer isDefault;

    /** 等级图片URL 20180607新增*/
    private String gradePicUrl;

    public String getGradePicUrl() {
        return gradePicUrl;
    }

    public void setGradePicUrl(String gradePicUrl) {
        this.gradePicUrl = gradePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.id
     *
     * @return the value of xd_salesman_grade.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.id
     *
     * @param id the value for xd_salesman_grade.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.name
     *
     * @return the value of xd_salesman_grade.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.name
     *
     * @param name the value for xd_salesman_grade.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.month_order_num
     *
     * @return the value of xd_salesman_grade.month_order_num
     *
     * @mbggenerated
     */
    public Integer getMonthOrderNum() {
        return monthOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.month_order_num
     *
     * @param monthOrderNum the value for xd_salesman_grade.month_order_num
     *
     * @mbggenerated
     */
    public void setMonthOrderNum(Integer monthOrderNum) {
        this.monthOrderNum = monthOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.storage_num
     *
     * @return the value of xd_salesman_grade.storage_num
     *
     * @mbggenerated
     */
    public Integer getStorageNum() {
        return storageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.storage_num
     *
     * @param storageNum the value for xd_salesman_grade.storage_num
     *
     * @mbggenerated
     */
    public void setStorageNum(Integer storageNum) {
        this.storageNum = storageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.create_user_id
     *
     * @return the value of xd_salesman_grade.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.create_user_id
     *
     * @param createUserId the value for xd_salesman_grade.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.create_time
     *
     * @return the value of xd_salesman_grade.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.create_time
     *
     * @param createTime the value for xd_salesman_grade.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.update_user_id
     *
     * @return the value of xd_salesman_grade.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.update_user_id
     *
     * @param updateUserId the value for xd_salesman_grade.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.update_time
     *
     * @return the value of xd_salesman_grade.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.update_time
     *
     * @param updateTime the value for xd_salesman_grade.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.is_del
     *
     * @return the value of xd_salesman_grade.is_del
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.is_del
     *
     * @param isDel the value for xd_salesman_grade.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_salesman_grade.is_default
     *
     * @return the value of xd_salesman_grade.is_default
     *
     * @mbggenerated
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_salesman_grade.is_default
     *
     * @param isDefault the value for xd_salesman_grade.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }
}