package net.dgg.cloud.dao;

import net.dgg.cloud.entity.CallRecord;

public interface CallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String callId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated
     */
    int insert(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated
     */
    int insertSelective(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated
     */
    CallRecord selectByPrimaryKey(String callId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CallRecord record);

    /**
     * 统计商务本月电话量
     *
     * @param salesmanId
     * @return
     */
    int selectCallCountByMonth(String salesmanId);
}