package net.dgg.cloud.dao;

import net.dgg.cloud.entity.ConRegion;

import java.util.List;

public interface ConRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_region
     *
     * @mbggenerated
     */
    int insert(ConRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_region
     *
     * @mbggenerated
     */
    int insertSelective(ConRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_region
     *
     * @mbggenerated
     */
    ConRegion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table con_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConRegion record);

    /**
     * 根据城市名称搜索城市id
     */
    ConRegion selectByCityName(ConRegion record);

    List<ConRegion> selectByPid(String pid);

    ConRegion selectByIdAndPid(String visitCity, String province);
}