package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdCallNum;

public interface XdCallNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_call_num
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_call_num
     *
     * @mbggenerated
     */
    int insert(XdCallNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_call_num
     *
     * @mbggenerated
     */
    int insertSelective(XdCallNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_call_num
     *
     * @mbggenerated
     */
    XdCallNum selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_call_num
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdCallNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_call_num
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdCallNum record);

    /**
     * 统计商务电话量
     *
     * @param salesmanId
     * @return
     */
    int selectCallCountByMonth(String salesmanId);
}