package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdClue;
import net.dgg.cloud.entity.XdResourceSource;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XdClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_clue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_clue
     *
     * @mbggenerated
     */
    int insert(XdClue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_clue
     *
     * @mbggenerated
     */
    int insertSelective(XdClue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_clue
     *
     * @mbggenerated
     */
    XdClue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_clue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdClue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_clue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdClue record);

    /**
     * 手机号查询
     *
     * @param phoneNo
     * @return
     */
    List<XdClue> selectSourceByPhone(@Param("phoneNo") String phoneNo);
}