package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdContacts;
import org.apache.xerces.xs.XSConstants;

import java.util.List;

public interface XdContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_contacts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contactsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_contacts
     *
     * @mbggenerated
     */
    int insert(XdContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_contacts
     *
     * @mbggenerated
     */
    int insertSelective(XdContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_contacts
     *
     * @mbggenerated
     */
    XdContacts selectByPrimaryKey(String contactsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_contacts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_contacts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdContacts record);

    /**
     * 根据资源id获取所有联系人信息
     *
     * @param record
     * @return
     */
    List<XdContacts> selectContactsList(XdContacts record);

    /**
     * 修改主联系人
     *
     * @param contactId
     * @return
     */
    int updateMainContactByResource(String contactId);

    /**
     * 获取资源的主联系人
     *
     * @param resourceId
     * @return
     */
    List<XdContacts> selectMainContactByResourceId(String resourceId);

}