package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdGeographyRecords;

public interface XdGeographyRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_geography_records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_geography_records
     *
     * @mbggenerated
     */
    int insert(XdGeographyRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_geography_records
     *
     * @mbggenerated
     */
    int insertSelective(XdGeographyRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_geography_records
     *
     * @mbggenerated
     */
    XdGeographyRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_geography_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdGeographyRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_geography_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdGeographyRecords record);
}