package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdIsDisplay;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XdIsDisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_is_display
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_is_display
     *
     * @mbggenerated
     */
    int insert(XdIsDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_is_display
     *
     * @mbggenerated
     */
    int insertSelective(XdIsDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_is_display
     *
     * @mbggenerated
     */
    XdIsDisplay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_is_display
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdIsDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_is_display
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdIsDisplay record);

    /**
     * 获取商务改资源的不再显示
     *
     * @param salesmanId
     * @param resourceId
     * @return
     */
    List<XdIsDisplay> selectBySalesmanIdAndResourceId(@Param("salesmanId") String salesmanId,@Param("resourceId") String resourceId);

}