package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdOnTime;
import org.apache.ibatis.annotations.Param;

public interface XdOnTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_on_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String onId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_on_time
     *
     * @mbggenerated
     */
    int insert(XdOnTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_on_time
     *
     * @mbggenerated
     */
    int insertSelective(XdOnTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_on_time
     *
     * @mbggenerated
     */
    XdOnTime selectByPrimaryKey(String onId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_on_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdOnTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_on_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdOnTime record);

    /**
     * 获取商务最新一条状态记录
     *
     * @param salesmanId
     * @return
     */
    XdOnTime selectLastBySalesman(String salesmanId);

    /**
     * 统计商务本月在线时长
     *
     * @param salesmanId
     * @return
     */
    Integer selectSumTimeLengthByMonth(String salesmanId);

    // V2 =============================================
    /**
     * 最新在线数据
     *
     * @param salesmanId
     * @return
     */
    XdOnTime selectLastOnTime(String salesmanId);

    /**
     * 繁忙时间
     *
     * @param salesmanId
     * @return
     */
    XdOnTime selectLastBusyOnTIme(@Param("salesmanId") String salesmanId);
}