package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdOrderNode;

import java.util.List;

public interface XdOrderNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_node
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_node
     *
     * @mbggenerated
     */
    int insert(XdOrderNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_node
     *
     * @mbggenerated
     */
    int insertSelective(XdOrderNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_node
     *
     * @mbggenerated
     */
    XdOrderNode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdOrderNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdOrderNode record);

    /**
     * 根据订单id获取订单节点
     */
    List<XdOrderNode> selectOrderNodeList(XdOrderNode record);
}