package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdOrderRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Map;

public interface XdOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_record
     *
     * @mbggenerated
     */
    int insert(XdOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_record
     *
     * @mbggenerated
     */
    int insertSelective(XdOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_record
     *
     * @mbggenerated
     */
    XdOrderRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdOrderRecord record);

    /**
     * 查询商务拒单次数
     *
     * @param commerceId
     * @param before7Day
     * @return
     */
    int selectRefuseCountBySalesman(@Param("commerceId") String commerceId,@Param("before7Day") String before7Day,@Param("nowTime") String nowTime);

    /**
     * 统计商务本月接单数
     *
     * @param salesmanId
     * @return
     */
    int selectAcceptCountByMonth(@Param("commerceId") String salesmanId);

}