package net.dgg.cloud.dao;

import net.dgg.cloud.dto.XdProductOrderDto;
import net.dgg.cloud.entity.XdProductOrder;

import java.util.List;

public interface XdProductOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_product_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_product_order
     *
     * @mbggenerated
     */
    int insert(XdProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_product_order
     *
     * @mbggenerated
     */
    int insertSelective(XdProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_product_order
     *
     * @mbggenerated
     */
    XdProductOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_product_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_product_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdProductOrder record);

    /**
     * 根据资源id查询订单详情
     * @param dto
     * @return
     */
    List<XdProductOrder> selectXdProductOrderList(XdProductOrderDto dto);

    /**
     * 资源订单 总计
     *
     * @param dto
     * @return
     */
    Integer selectXdProductOrderCount(XdProductOrderDto dto);

    /**
     * 通过客户手机号查询订单信息
     * @param dto
     * @return
     */
    List<XdProductOrder> selectXdProductOrderByPhone(XdProductOrderDto dto);

    /**
     * 总条数
     * @param dto
     * @return
     */
    int selectCount(XdProductOrderDto dto);
}