package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdResourceSource;

public interface XdResourceSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_source
     *
     * @mbggenerated
     */
    int insert(XdResourceSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_source
     *
     * @mbggenerated
     */
    int insertSelective(XdResourceSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_source
     *
     * @mbggenerated
     */
    XdResourceSource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdResourceSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdResourceSource record);

    XdResourceSource selectByCode(String sourceCode);
}