package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdResourceDistribution;

import java.util.Map;

public interface XdResourceDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_distribution
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String distributionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_distribution
     *
     * @mbggenerated
     */
    int insert(XdResourceDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_distribution
     *
     * @mbggenerated
     */
    int insertSelective(XdResourceDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_distribution
     *
     * @mbggenerated
     */
    XdResourceDistribution selectByPrimaryKey(String distributionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_distribution
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdResourceDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_distribution
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdResourceDistribution record);

    int updateLastDistribution(Map<String, Object> params);

    int updateResponseFlag(Map<String, Object> params);
}