package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdResourceAudit;

public interface XdResourceAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_audit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_audit
     *
     * @mbggenerated
     */
    int insert(XdResourceAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_audit
     *
     * @mbggenerated
     */
    int insertSelective(XdResourceAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_audit
     *
     * @mbggenerated
     */
    XdResourceAudit selectByPrimaryKey(String auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdResourceAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdResourceAudit record);
}