package net.dgg.cloud.dao;

import net.dgg.cloud.dto.XdResourcesFollowDto;
import net.dgg.cloud.entity.XdResourceFollow;

import java.util.List;

public interface XdResourceFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_follow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_follow
     *
     * @mbggenerated
     */
    int insert(XdResourceFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_follow
     *
     * @mbggenerated
     */
    int insertSelective(XdResourceFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_follow
     *
     * @mbggenerated
     */
    XdResourceFollow selectByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_follow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdResourceFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_follow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdResourceFollow record);

    /**
     * 根据资源id获取所有该资源跟进记录
     */
    List<XdResourceFollow> selectXdResourceFollowList(XdResourcesFollowDto dto);

    /**
     * 统计总条数
     */
    int selectCount(XdResourcesFollowDto dto);
}