package net.dgg.cloud.dao;

import net.dgg.cloud.dto.XdResourceVisitDto;
import net.dgg.cloud.entity.XdResourceVisit;

import java.util.List;

public interface XdResourceVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_visit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String visitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_visit
     *
     * @mbggenerated
     */
    int insert(XdResourceVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_visit
     *
     * @mbggenerated
     */
    int insertSelective(XdResourceVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_visit
     *
     * @mbggenerated
     */
    XdResourceVisit selectByPrimaryKey(String visitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_visit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdResourceVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_resource_visit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdResourceVisit record);

    /**
     * 根据资源id获取上门列表信息
     */
    List<XdResourceVisit> selectXdResourceVisitList(XdResourceVisitDto dto);

    /**
     * 获取总条数
     */
    Integer selectCount(XdResourceVisitDto dto);

    /**
     * 统计商务本月上门量
     *
     * @param salesmanId
     * @return
     */
    int selectVisitCountByMonth(String salesmanId);
}