package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdServiceProcess;

public interface XdServiceProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_process
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_process
     *
     * @mbggenerated
     */
    int insert(XdServiceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_process
     *
     * @mbggenerated
     */
    int insertSelective(XdServiceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_process
     *
     * @mbggenerated
     */
    XdServiceProcess selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdServiceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdServiceProcess record);
}