package net.dgg.cloud.dao;

import net.dgg.cloud.entity.XdServiceType;

public interface XdServiceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_type
     *
     * @mbggenerated
     */
    int insert(XdServiceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_type
     *
     * @mbggenerated
     */
    int insertSelective(XdServiceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_type
     *
     * @mbggenerated
     */
    XdServiceType selectByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdServiceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_service_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdServiceType record);
}